package:
  name: hla-polysolver
  version: "1.0.0"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/hla-polysolver.git

build:
  number: 21

requirements:
  build:
    - perl 5.22.*
    - perl-app-cpanminus
    - novoalign
    - gcc
    - make
    - zlib
  run:
    - zlib
    - make
    - python 2.7.*
    - perl 5.22.*
    - samtools <=0.1.18
    - novoalign
    - mutect <=1.1.6
    - java-jdk 7.*
    - perl-posix
    - perl-bioperl
    - perl-list-util
    - perl-list-moreutils
    - perl-parallel-forkmanager
    - perl-data-dumper
    - perl-bio-db-sam
    - perl-array-utils
    - perl-vcftools-vcf <=0.953
about:
  home: https://github.com/jason-weirather/hla-polysolver
  license: BSD
  license_file: LICENSE
