library("ggplot2")
library("gridExtra")
cd4 <- read.table("convCD4.out", header=TRUE)
cd4_CB <- subset(cd4, select=="CB")
cd4_CL <- subset(cd4, select=="CL")
cd4_plot1 <- ggplot() + geom_point(data=cd4, aes(x=UMAP_1, y=UMAP_2, color=NeoTCR4), alpha=1) + scale_colour_gradient(low="lightgrey", high="blue") + theme(plot.title = element_text(size=14, face="bold", hjust=0.5)) + ggtitle("NeoTCR4_AUCscore for convCD4")
# range(cd4$UMAP_1)
# range(cd4$UMAP_2)
cd4_plot2 <- ggplot() + geom_point(data=cd4, aes(x=UMAP_1, y=UMAP_2, color=NeoTCR4), alpha=1) + scale_colour_gradient(low="lightgrey", high="blue") + geom_point(data=cd4_CL, aes(x=UMAP_1, y=UMAP_2), color="green") + geom_point(data=cd4_CB, aes(x=UMAP_1, y=UMAP_2), color="red") + theme(plot.title = element_text(size=14, face="bold", hjust=0.5)) + ggtitle("NeoTCR4_AUCscore for convCD4 (selected CB highlighted)") + annotate("point", x = 7.75, y = -2.5, colour="red", size=1.5) + annotate("text", x = 9.5, y = -2.5, label = "max AUC") + annotate("point", x=7.75, y = -3.25, colour="green", size=1.5) + annotate("text", x = 9.25, y = -3.25, label = "same cl") + coord_cartesian(xlim=c(-14,6), ylim=c(-7, 8), clip = "off")
treg <- read.table("TregCD4.out", header=TRUE)
treg_CB <- subset(treg, select=="CB")
treg_CL <- subset(treg, select=="CL")
treg_plot1 <- ggplot() + geom_point(data=treg, aes(x=UMAP_1, y=UMAP_2, color=NeoTCR4), alpha=1) + scale_colour_gradient(low="lightgrey", high="blue") + theme(plot.title = element_text(size=14, face="bold", hjust=0.5)) + ggtitle("NeoTCR4_AUCscore for TregCD4")
# range(cd4$UMAP_1)
# range(cd4$UMAP_2)
treg_plot2 <- ggplot() + geom_point(data=treg, aes(x=UMAP_1, y=UMAP_2, color=NeoTCR4), alpha=1) + scale_colour_gradient(low="lightgrey", high="blue") + geom_point(data=treg_CL, aes(x=UMAP_1, y=UMAP_2), color="green") + geom_point(data=treg_CB, aes(x=UMAP_1, y=UMAP_2), color="red") + theme(plot.title = element_text(size=14, face="bold", hjust=0.5)) + ggtitle("NeoTCR4_AUCscore for TregCD4 (selected CB highlighted)") + annotate("point", x = 7.75, y = -2.5, colour="red", size=1.5) + annotate("text", x = 9.5, y = -2.5, label = "max AUC") + annotate("point", x=7.75, y = -3.25, colour="green", size=1.5) + annotate("text", x = 9.25, y = -3.25, label = "same cl") + coord_cartesian(xlim=c(-14,6), ylim=c(-7, 8), clip = "off")
cd8 <- read.table("CD8.out", header=TRUE)
cd8_CB <- subset(cd8, select=="CB")
cd8_CL <- subset(cd8, select=="CL")
cd8_plot1 <- ggplot() + geom_point(data=cd8, aes(x=UMAP_1, y=UMAP_2, color=NeoTCR8), alpha=1) + scale_colour_gradient(low="lightgrey", high="blue") + theme(plot.title = element_text(size=14, face="bold", hjust=0.5)) + ggtitle("NeoTCR8_AUCscore for CD8")
cd8_plot2 <- ggplot() + geom_point(data=cd8, aes(x=UMAP_1, y=UMAP_2, color=NeoTCR8), alpha=1) + scale_colour_gradient(low="lightgrey", high="blue") + geom_point(data=cd8_CL, aes(x=UMAP_1, y=UMAP_2), color="green") + geom_point(data=cd8_CB, aes(x=UMAP_1, y=UMAP_2), color="red") + theme(plot.title = element_text(size=14, face="bold", hjust=0.5)) + ggtitle("NeoTCR8_AUCscore for CD8 (selected CB highlighted)") + annotate("point", x = 7.75, y = -2.5, colour="red", size=1.5) + annotate("text", x = 9.5, y = -2.5, label = "max AUC") + annotate("point", x=7.75, y = -3.25, colour="green", size=1.5) + annotate("text", x = 9.25, y = -3.25, label = "same cl") + coord_cartesian(xlim=c(-14,6), ylim=c(-7, 8), clip = "off")
pdf("AUCscore.pdf", height=13.5, width=16)
grid.arrange(cd4_plot1, cd4_plot2, treg_plot1, treg_plot2, cd8_plot1, cd8_plot2, ncol=2)
dev.off()
