---
title: "Example notebook for 10X analysis pipeline"
output: html_notebook
---

---------------------
This notebook contains an example analysis of CITE-seq data from the VHIO
collaboration (EXP 421 on Benchling).
Portions pertaining to detailed questions relevant to this project, but not
done more generally, have been removed removed. This is to better demonstrate
the current "standard" analysis approach.

Author: Seon Kinrot (RootPath Genomics)
---------------------

Define folders, load libraries

-----------------------

```{r}
library(Seurat)
library(ggplot2)
library(patchwork)
library(rBCS)

master_dir <- '/folder/with/raw/data/'
code_dir <- '/path/to/this/repository'
analysis_dir <- '/folder/to/save/analysis/results/in/'
r_fls <- list.files(code_dir, "[.]R$", full.names = T)
for (fl in r_fls) {
  source(fl)
}
```

Load all data and generate list of GEX, CSP and VDJ data for each individual
sample
```{r}
# these project names are taken from the VHIO CITE-seq data (EXP421)
project_names <- c("0008_pre_CD3", "0008_pre_PD1",
                   "0008_post_CD3", "0008_post_PD1",
                   "0029_pre_CD3", "0029_pre_PD1",
                   "0029_post_CD3", "0029_post_PD1")
n_projects <- length(project_names)

gex_list <- vector(mode = "list", length = n_projects)
vdj_list <- vector(mode = "list", length = n_projects)
csp_list <- vector(mode = "list", length = n_projects)

for (iproject in seq_len(n_projects)) {
  # this folder naming was definde when runninng CellRanger for this project
  gex_dir <- paste0(master_dir, "GEX", iproject,"_count/outs/")
  gex_list[[iproject]] <- load_seurat(prj_dir = gex_dir,
                                      prj_nm = project_names[iproject])

  csp_dir <- paste0(master_dir, "CSP", iproject,"_count/outs/")
  csp_list[[iproject]] <- load_seurat(prj_dir = csp_dir,
                                      prj_nm = project_names[iproject])

  vdj_dir <- paste0(master_dir, "VDJ", iproject,"_count/outs/")
  vdj_list[[iproject]] <- load_vdj(tcr_dir = vdj_dir)
}
```

Initiate list of cell barcode lists. This will be used to save barcodes that
passed QC in each sample, before applying it in one go
```{r}
cells_lists <- vector(mode = "list", length = n_projects)
```

-----------------------------------------

Perform QC for all GEX data.
The following brackets are performed one after the other for each sample, then
repeated until all samples have been through QC.

-----------------------
```{r}
iproject <- 1
srt_obj <- gex_list[[iproject]]
# this generates the unfiltered QC plots, as well as adds %mitochondrial,
# %ribosomal and cell cycle scoring to object metadata
qc_out <- run_qc(srt_obj, return_object = TRUE)
ggsave(paste(analysis_dir,
             paste0(project_name, "_preQC.png"),
             sep = "/"),
       width = 8,
       height = 6)
# save object with metadata
srt_obj <- qc_out$filtered_seurat
gex_list[[iproject]] <- srt_obj
```

```{r}
# find appropriate QC filters for this sample. This bracket can be run
# repeatedly without affecting srt_obj
qc_out <- run_qc(srt_obj, max_fsets = c(10, 100),
                 min_feats = 10**2., max_feats = 10**3.5,
                 min_umi = 10**3., max_umi = 10**4.)
```

```{r}
# save post-QC plot
ggsave(filename = paste(analysis_dir,
                        paste0(project_name, "_postQC.png"),
                        sep = "/"),
       width = 8,
       height = 6)
keep_bcodes <- qc_out$keep_barcodes
cells_lists[[iproject]] <- keep_bcodes
```

Return to beginning of this section and advance iproject, until all samples
have been through QC

------------------------

Run normalization, integration and clustering, then save data

------------------------

Apply QC filters to all samples
```{r}
for (iproject in seq_len(n_projects)) {
  srt_obj <- gex_list[[iproject]]
  keep_cells <- cells_lists[[iproject]]
  print(paste(project_names[iproject], length(colnames(srt_obj)),
              length(keep_cells), sep = "; "))
  srt_obj <- srt_obj[, keep_cells]
  gex_list[[iproject]] <- srt_obj
}
```

Now, all data needs to be merged independently
```{r}
# set maxSize to 16 GB to avoid crashing
options(future.globals.maxSize = 16*2^30)
options(future.seed = TRUE)

# make sure project names are respected
names(gex_list) <- project_names
names(csp_list) <- project_names
names(vdj_list) <- project_names

# groups within which to combine clone counts for VDJ
sample_groups <- list("0008_pre" = c(1, 2),
                      "0008_post" = c(3, 4),
                      "0029_pre" = c(5, 6),
                      "0029_post" = c(7, 8))

# Time this, just so it's easier to keep track
start_time <- Sys.time()
# Merge VDJ
merged_vdj <- merge_vdj(vdj_list = vdj_list,
                        sample_groups = sample_groups,
                        merge_clone_id = TRUE,
                        merge_clonality = TRUE)
print("Merged VDJ data")
vdj_time <- Sys.time()
print(vdj_time - start_time)

# Merge CSP
integrated_csp <- integrate_datasets(srt_list = csp_list,
                                     normalization_method = "CLR",
                                     nfeatures = 2000,
                                     readd_counts = TRUE)
csp_time <- Sys.time()
print("Merged CSP data")
print(csp_time - vdj_time)

integrated_gex <- integrate_datasets(srt_list = gex_list,
                                     normalization_method = "SCT",
                                     regress = c("percent_mitochondrial",
                                                 "nFeature_RNA"),
                                     nfeatures = 3000,
                                     rmv_grep = "TR[AB]V",
                                     readd_counts = TRUE)
gex_time <- Sys.time()
print("Merged GEX data")
print(gex_time - csp_time)
```

Cluster each dataset separately
```{r}
# scale and cluster CSP
integrated_csp <- ScaleData(object = integrated_csp, verbose = FALSE,
                            vars.to.regress = "nFeature_RNA")
integrated_csp <- cluster_seurat(srt_obj = integrated_csp)
# cluster GEX
integrated_gex <- cluster_seurat(srt_obj = integrated_gex)
```

Merge all data into a single Seurat object
```{r}
# merge GEX and CSP
integrated_gex <- add_assay(main_srt = integrated_gex,
                            secondary_srt = integrated_csp,
                            assay = "RNA",
                            new_name = "ADT",
                            add_reductinos = TRUE,
                            filter_main = TRUE)
integrated_gex <- add_assay(main_srt = integrated_gex,
                            secondary_srt = integrated_csp,
                            assay = "integrated",
                            new_name = "ADT_integrated",
                            add_reductinos = TRUE,
                            filter_main = TRUE)
# filter_main specifies whether we only keep barcodes that have both GEX and
# CSP data. To keep all GEX barcodes regardless of whether they have CSP,
# set to FALSE

# add metadata containing cluster IDs
for (res in c(0.4, 0.8, 1.2)) {
  meta_name <- paste0("integrated_snn_res.", res)
  integrated_gex <- AddMetaData(object = integrated_gex,
                                metadata = integrated_csp[[meta_name]],
                                col.name = paste("adt", meta_name, sep = "_"))
}

# add Yost exhaustion score
var_feats<- integrated_gex@assays$integrated@var.features
yost_exhaustion<- c("CTSW", "GNLY", "PRF1", "SLA2", "HAVCR2", "GZMB", "ITGAE",
                    "GALNT2", "ACP5", "CXCR6", "ENTPD1", "KRT86", "TIGIT",
                    "LAYN", "JAML", "AC092580.4", "AHI1", "ALOX5AP", "SYNGR2",
                    "CARD16", "FKBP1A", "GOLIM4", "SNX9", "TNFRSF18", "ZBED2",
                    "TNFRSF9", "VCAM1", "CXCL13", "GEM")
yost_module <- yost_exhaustion[yost_exhaustion %in% var_feats]
integrated_gex <- AddModuleScore(integrated_gex,
                                 features = list(yost_module),
                                 name = "Yost_exhaustion_score")

# add VDJ data
integrated_gex <- add_vdj(srt_obj = integrated_gex,
                          clone_info = merged_vdj,
                          use_frequency = TRUE,
                          verbose = TRUE)
```

Save the integrated data
```{r}
write_csv(merged_vdj,
          file = paste0(analysis_dir, "all_tcrs.csv"))
saveRDS(integrated_csp,
        file = paste0(analysis_dir, "integrated_csp.rds"))
saveRDS(integrated_gex,
        file = paste0(analysis_dir, "integrated_seurat.rds"))
ExportSeurat(integrated_gex,
             paste0(analysis_dir, "integrated_data_BBrowser.bcs"),
             author = "SK",
             raw.rna = "integrated",
             norm.rna = "integrated",
             raw.adt = "ADT_integrated",
             norm.adt = "ADT_integrated")
```

----------------------------------------

The following section will deal with generating plots

---------------------------------------

Some sanity checks to see that integration wasn't complete bogus
```{r}
# show UMAP for cells originating from each sample
samples_gex_plot <- DimPlot(object = integrated_gex, split.by = "orig.ident",
                            group.by = "orig.ident") +
  ggtitle("GEX UMAP per sample of origin")
ggsave(paste0(analysis_dir, "GEX_UMAP_by_sample.png"),
       samples_gex_plot,
       width = 16, height = 12)
print(samples_gex_plot)
# repeat for CSP UMAP
samples_csp_plot <- DimPlot(object = integrated_gex, split.by = "orig.ident",
                            group.by = "orig.ident",
                            reduction = "adt_integrated_umap") +
  ggtitle("CSP UMAP per sample of origin")
ggsave(paste0(analysis_dir, "CSP_UMAP_by_sample.png"),
       samples_csp_plot,
       width = 16, height = 12)
print(samples_csp_plot)
```

```{r}
# show UMAP for cells split by predicted cell cycle phase
cc_gex_plot <- DimPlot(object = integrated_gex, split.by = "Phase",
                       group.by = "Phase") +
  ggtitle("GEX UMAP per cell cycle phase")
ggsave(paste0(analysis_dir, "GEX_UMAP_by_ccPhase.png"),
       cc_gex_plot,
       width = 16, height = 6)
print(cc_gex_plot)
# repeat for CSP UMAP
cc_csp_plot <- DimPlot(object = integrated_gex, split.by = "Phase",
                       group.by = "Phase",
                       reduction = "adt_integrated_umap") +
  ggtitle("CSP UMAP per cell cycle phase")
ggsave(paste0(analysis_dir, "CSP_UMAP_by_ccPhase.png"),
       cc_csp_plot,
       width = 16, height = 6)
print(cc_csp_plot)
```

Show clusters, and characterize with feature plots and clonality
```{r}
# plot clustering
gex_cluster_plt<- DimPlot(object = integrated_gex,
                          group.by = "integrated_snn_res.0.4",
                          label = T, label.box = T, pt.size = 1) +
  DimPlot(object = integrated_srt,
          group.by = "integrated_snn_res.0.8",
          label = T, label.box = T, pt.size = 1) +
  DimPlot(object = integrated_srt,
          group.by = "integrated_snn_res.1.2",
          label = T, label.box = T, pt.size = 1)
ggsave(filename = paste0(analysis_dir, "integrated_GexClusterByRes_GexUMAP.png"),
       plot = gex_cluster_plt,
       width = 20,
       height = 6)
print(gex_cluster_plt)

#CSP clusters
csp_cluster_plt<- DimPlot(object = integrated_gex,
                          group.by = "adt_integrated_snn_res.0.4",
                          reduction = "adt_integrated_umap",
                          label = T, label.box = T, pt.size = 1) +
  DimPlot(object = integrated_srt,
          group.by = "adt_integrated_snn_res.0.8",
          reduction = "adt_integrated_umap",
          label = T, label.box = T, pt.size = 1) +
  DimPlot(object = integrated_srt,
          group.by = "adt_integrated_snn_res.1.2",
          reduction = "adt_integrated_umap",
          label = T, label.box = T, pt.size = 1)
ggsave(filename = paste0(analysis_dir, "integrated_CspClusterByRes_CspUMAP.png"),
       plot = csp_cluster_plt,
       width = 20,
       height = 6)
print(csp_cluster_plt)
```

A useful plot that can only be done with CITE-seq
```{r}
my_palette <- CustomPalette(low = "blue", high = "red", mid = "grey")
# show protein CD4 and CD8A expression
gex_cd48_plot <- FeaturePlot(integrated_gex,
                            features = c("CD4-totSeq", "CD8A-totSeq"),
                            cols = my_palette) +
  xlab("GEX_UMAP_1") + ylab("GEX_UMAP_2")
ggsave(filename = paste0(analysis_dir, "integrated_CD4_CD8_GexUMAP.png"),
       plot = gex_cd48_plot,
       width = 8,
       height = 6)
print(gex_cd48_plot)

# repeat for CSP
csp_cd48_plot <- FeaturePlot(integrated_gex,
                            features = c("CD4-totSeq", "CD8A-totSeq"),
                            reduction = "adt_integrated_umap",
                            cols = my_palette) +
  xlab("CSP_UMAP_1") + ylab("CSP_UMAP_2")
ggsave(filename = paste0(analysis_dir, "integrated_CD4_CD8_CspUMAP.png"),
       plot = csp_cd48_plot,
       width = 8,
       height = 6)
print(csp_cd48_plot)
```

FeaturePlots for Yost et al markers
```{r}
yost_markers<- c("CD3D","CD8A", "CD4", "FOXP3", "CCR7", "IL26", "CD200", "EOMES", "KLRD1", "IFNG", "HAVCR2")
yost_markers <- yost_markers[yost_markers %in% var_feats]
yost_fp<- FeaturePlot(integrated_gex,
                      features = c(yost_markers, "Yost_exhaustion_score1")) +
  xlab("GEX_UMAP_1") + ylab("GEX_UMAP_2")
ggsave(filename = paste0(analysis_dir, "integrated_Yost_FP_GexUMAP.png"),
       plot = yost_fp,
       width = 12,
       height = 8)
print(yost_fp)
```

Clonality
```{r}
# first with GEX UMAP
gex_clone_plot <- plot_clonality(integrated_gex,
                                 save_path = paste0(analysis_dir,
                                                    "integrated_TCRclonality_GexUMAP.png"))
print(gex_clone_plot)

# now for CSP
csp_clone_plot <- plot_clonality(integrated_gex,
                                 axes = c("ADT_integrated_UMAP_1",
                                          "ADT_integrated_UMAP_2"),
                                 axes_names = c("CSP_UMAP_1",
                                                "CSP_UMAP_2"),
                                 save_path = paste0(analysis_dir,
                                                    "integrated_TCRclonality_CspUMAP.png"))
print(csp_clone_plot)
```

Generate figures with Danielle's gene list
```{r}
# firstGEX UMAPs
plot_dir <- paste0(analysis_dir, "/Feature_plots_GEX/")
if (!dir.exists(plot_dir)) {
  dir.create(plot_dir)
}
temp <- gen_feature_plots(gex_seurat = integrated_gex, plot_dir = plot_dir)

# then CSP
plot_dir <- paste0(analysis_dir, "/Feature_plots_CSP/")
if (!dir.exists(plot_dir)) {
  dir.create(plot_dir)
}
temp <- gen_feature_plots(gex_seurat = integrated_gex, plot_dir = plot_dir,
                          axes = c("ADT_integrated_UMAP_1",
                                   "ADT_integrated_UMAP_2"),
                          axes_names = c("CSP_UMAP_1",
                                         "CSP_UMAP_2"))
```

-----------------------------------
