require(Seurat)
suppressMessages(suppressWarnings(require(tidyverse)))
args = commandArgs(T)
## input file: 
## 1) a seurat object (sc_seurat_obj.rds), must contain a clonotype_id slot in metadata.
##	usally generated by analysis.10x.R
## 2) a compared TCR clonotype file with shared clonotypes, 
##	usually generated by compare_multi_clonotypes_add_consensus_annotations.files.R


load(args[1])
print("load RData .. OK")
# load("sc_seurat_obj.RData")
csv_file = "shared.clonotypes.frequency.csv"
clonotype_data = read.table(csv_file, sep=",", header=TRUE, stringsAsFactors=FALSE)
print("read csv   .. OK")
#clonotype_data = read.csv("G179E3-PBMC-CD8_G179E1-TILs-CD3T_frequency.csv", header=T)
# stringsAsFactors=FALSE)
# please check this line: usually default column is 2nd column for extract clonotype name.
clonotype_names = clonotype_data[,2] 
print("extract name .. OK")
cell_names = rownames(sc_seurat_obj@meta.data %>% filter(sc_seurat_obj@meta.data$clonotype_id %in% clonotype_names))
print("cell names .. OK")
# draw plot
p = DimPlot(object = sc_seurat_obj,cells.highlight = cell_names) +
  scale_color_manual(labels = c("Unselected","shared cells"),values = c("grey","red")) +
  labs(color = "")
ggsave(filename="DimPlot.show.cells.on.Clusters.png", plot=p, path=".")
